# Generated by Django 4.0.5 on 2022-06-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='user_pictures/IMG_8678.jpg', upload_to='post_pictures/<django.db.models.fields.related.OneToOneField>', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='user_pictures/<django.db.models.query_utils.DeferredAttribute object at 0x000001BFAFA91070>/', verbose_name='Фото профиля'),
        ),
    ]
