# Generated by Django 4.0.5 on 2022-08-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
