# Generated by Django 4.0.5 on 2022-08-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_music_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Днюха'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('ХЗ', 'Другое')], max_length=30, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='who_for_me',
            field=models.CharField(max_length=255, null=True, verbose_name='Кто ты Эльдару?'),
        ),
        migrations.AlterField(
            model_name='music',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
